/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import BD.ConexionBD;
import Controladores.EventoControlador;
import Controladores.LoginControlador;
import Controladores.RecordatorioControlador;
import Controladores.RegistroControlador;
import Modelos.FondoPanel;
import Modelos.SesionUsuario;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
       ImageIcon fondoIcon = new ImageIcon(getClass().getResource("/IMG/imgCOmpleta.jpg"));
    Image imagen = fondoIcon.getImage();

    // Aplica el fondo al frame
    FondoPanel fondo = new FondoPanel(imagen);
    setContentPane(fondo); // Aplica el fondo ANTES de initComponents()

        initComponents();
        personalizarMenu();
        JPanel recordatorios = new PanelListaRecordatorios();
    Recordatorios.add(recordatorios);
    recordatorios.setSize(new Dimension(400, 300));

    setLocationRelativeTo(null); // Centrar ventana

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblOpcion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbtnAgenda = new javax.swing.JButton();
        jbtnReporteGrafico = new javax.swing.JButton();
        jbtnUsuario = new javax.swing.JButton();
        Recordatorios = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblOpcion.setText("Elija una opcion");

        jButton1.setText("Eventos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnAgenda.setText("Reporte de texto");

        jbtnReporteGrafico.setText("Reporte grafico");

        jbtnUsuario.setText("Cambiar usuario");
        jbtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUsuarioActionPerformed(evt);
            }
        });

        Recordatorios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout RecordatoriosLayout = new javax.swing.GroupLayout(Recordatorios);
        Recordatorios.setLayout(RecordatoriosLayout);
        RecordatoriosLayout.setHorizontalGroup(
            RecordatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        RecordatoriosLayout.setVerticalGroup(
            RecordatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnAgenda, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnReporteGrafico, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnUsuario))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(Recordatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Recordatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jbtnUsuario)
                        .addGap(53, 53, 53)
                        .addComponent(jlblOpcion)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnAgenda)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnReporteGrafico)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AgendaPersonalizada vista = new AgendaPersonalizada();
        EventoControlador controlador = new EventoControlador();
        vista.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUsuarioActionPerformed
        
        SesionUsuario.cerrarSesion();
        Login_VIEW log = new Login_VIEW();
        Controladores.LoginControlador contLogin = new LoginControlador(log);
        log.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbtnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    private void personalizarMenu() {
    // Desactivar layout automático
    setLayout(null);

    // Título
    jlblOpcion.setText("ELIJA UNA OPCIÓN");
    jlblOpcion.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
    jlblOpcion.setBounds(50, 20, 300, 40);
    add(jlblOpcion);

    // Botón Eventos
    jButton1.setText("Eventos");
    jButton1.setBackground(new java.awt.Color(0, 123, 255));
    jButton1.setForeground(java.awt.Color.WHITE);
    jButton1.setFocusPainted(false);
    jButton1.setBounds(50, 80, 180, 40);
    add(jButton1);

    // Botón Reporte Texto
    jbtnAgenda.setText("Reporte de texto");
    jbtnAgenda.setBackground(new java.awt.Color(40, 167, 69));
    jbtnAgenda.setForeground(java.awt.Color.WHITE);
    jbtnAgenda.setFocusPainted(false);
    jbtnAgenda.setBounds(50, 130, 180, 40);
    add(jbtnAgenda);

    // Botón Reporte Gráfico
    jbtnReporteGrafico.setText("Reporte gráfico");
    jbtnReporteGrafico.setBackground(new java.awt.Color(23, 162, 184));
    jbtnReporteGrafico.setForeground(java.awt.Color.WHITE);
    jbtnReporteGrafico.setFocusPainted(false);
    jbtnReporteGrafico.setBounds(50, 180, 180, 40);
    add(jbtnReporteGrafico);

    // Botón Cambiar usuario
    jbtnUsuario.setText("Cambiar usuario");
    jbtnUsuario.setBackground(new java.awt.Color(255, 193, 7));
    jbtnUsuario.setForeground(java.awt.Color.BLACK);
    jbtnUsuario.setFocusPainted(false);
    jbtnUsuario.setBounds(50, 230, 180, 40);
    add(jbtnUsuario);

    // Panel Recordatorios (NO TOCAR)
    Recordatorios.setBounds(270, 20, 450, 400);
    add(Recordatorios);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Recordatorios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbtnAgenda;
    private javax.swing.JButton jbtnReporteGrafico;
    private javax.swing.JButton jbtnUsuario;
    private javax.swing.JLabel jlblOpcion;
    // End of variables declaration//GEN-END:variables
}
